export const productos = [
  {
    nombre: "Remera básica blanca",
    descripcion: "Cómoda remera de algodón en color blanco.",
    precio: 19.99,
    imagen: "/remerapng.png",
    categoria: "remeras",
    id: 1,
    tipo: "hombre",
    pais: "argentina",
  },
  {
    nombre: "Remera estampada floral",
    descripcion: "Remera con estampado floral ",
    precio: 24.99,
    imagen: "/remerapng.png",
    categoria: "remeras",
    id: 2,
    tipo: "hombre",
    pais: "argentina",
  },
  {
    nombre: "Remera de rayas",
    descripcion: "Remera a rayas de colores ",
    precio: 22.99,
    imagen: "/remerapng.png",
    categoria: "remeras",
    id: 3,
    tipo: "hombre",
    pais: "argentina",
  },
  {
    nombre: "Remera de manga larga",
    descripcion: "Remera cómoda con manga larga",
    precio: 29.99,
    imagen: "/remerapng.png",
    categoria: "remeras",
    id: 4,
    tipo: "hombre",
    pais: "argentina",
  },
  {
    nombre: "Remera gráfica",
    descripcion: "Remera con impresión gráfica ",
    precio: 26.99,
    imagen: "/remerapng.png",
    categoria: "remeras",
    id: 5,
    tipo: "hombre",
    pais: "argentina",
  },
  {
    nombre: "Remera de cuello en V",
    descripcion: "Remera con cuello en V ",
    precio: 21.99,
    imagen: "/remerapng.png",
    categoria: "remeras",
    id: 6,
    tipo: "hombre",
    pais: "argentina",
  },
  {
    nombre: "Remera sin mangas",
    descripcion: "Remera sin mangas para el verano.",
    precio: 18.99,
    imagen: "/remerapng.png",
    categoria: "remeras",
    id: 7,
    tipo: "hombre",
    pais: "argentina",
  },
  {
    nombre: "Remera con mensaje",
    descripcion: "Remera con mensaje inspirador",
    precio: 23.99,
    imagen: "/remerapng.png",
    categoria: "remeras",
    id: 8,
    tipo: "hombre",
    pais: "argentina",
  },
  {
    nombre: "Remera deportiva",
    descripcion: "Remera deportiva",
    precio: 27.99,
    imagen: "/remerapng.png",
    categoria: "remeras",
    id: 9,
    tipo: "hombre",
    pais: "argentina",
  },
  {
    nombre: "Remera estilo vintage",
    descripcion: "Remera con diseño vintage",
    precio: 25.99,
    imagen: "/remerapng.png",
    categoria: "remeras",
    id: 10,
    tipo: "hombre",
    pais: "argentina",
  },
  {
    nombre: "Remera deportiva",
    descripcion: "Remera deportiva de tejido transpirable.",
    precio: 27.99,
    imagen:
      "https://portsaid.vtexassets.com/arquivos/ids/343852-1200-auto?width=1200&height=auto&aspect=true",
    categoria: "pantalones",
    id: 11,
    tipo: "mujer",
    pais: "argentina",
  },
  {
    nombre: "Remera deportiva",
    descripcion: "Remera deportiva de tejido transpirable.",
    precio: 27.99,
    imagen:
      "https://portsaid.vtexassets.com/arquivos/ids/343852-1200-auto?width=1200&height=auto&aspect=true",
    categoria: "pantalones",
    id: 12,
    tipo: "mujer",
    pais: "argentina",
  },
  {
    nombre: "Remera deportiva",
    descripcion: "Remera deportiva de tejido transpirable.",
    precio: 27.99,
    imagen:
      "https://portsaid.vtexassets.com/arquivos/ids/343852-1200-auto?width=1200&height=auto&aspect=true",
    categoria: "pantalones",
    id: 13,
    tipo: "mujer",
    pais: "argentina",
  },
  {
    nombre: "Remera deportiva",
    descripcion: "Remera deportiva de tejido transpirable.",
    precio: 27.99,
    imagen:
      "https://portsaid.vtexassets.com/arquivos/ids/343852-1200-auto?width=1200&height=auto&aspect=true",
    categoria: "pantalones",
    id: 14,
    tipo: "mujer",
    pais: "argentina",
  },
  {
    nombre: "Remera deportiva",
    descripcion: "Remera deportiva de tejido transpirable.",
    precio: 27.99,
    imagen:
      "https://portsaid.vtexassets.com/arquivos/ids/343852-1200-auto?width=1200&height=auto&aspect=true",
    categoria: "pantalones",
    id: 15,
    tipo: "mujer",
    pais: "argentina",
  },
  {
    nombre: "Remera deportiva",
    descripcion: "Remera deportiva de tejido transpirable.",
    precio: 27.99,
    imagen:
      "https://portsaid.vtexassets.com/arquivos/ids/343852-1200-auto?width=1200&height=auto&aspect=true",
    categoria: "pantalones",
    id: 16,
    tipo: "mujer",
    pais: "argentina",
  },
  {
    nombre: "Remera deportiva",
    descripcion: "Remera deportiva de tejido transpirable.",
    precio: 27.99,
    imagen:
      "https://portsaid.vtexassets.com/arquivos/ids/343852-1200-auto?width=1200&height=auto&aspect=true",
    categoria: "pantalones",
    id: 17,
    tipo: "mujer",
  },
  {
    nombre: "Remera deportiva",
    descripcion: "Remera deportiva de tejido transpirable.",
    precio: 27.99,
    imagen:
      "https://portsaid.vtexassets.com/arquivos/ids/343852-1200-auto?width=1200&height=auto&aspect=true",
    categoria: "pantalones",
    id: 18,
    tipo: "mujer",
  },
  {
    nombre: "Remera deportiva",
    descripcion: "Remera deportiva de tejido transpirable.",
    precio: 27.99,
    imagen:
      "https://portsaid.vtexassets.com/arquivos/ids/343852-1200-auto?width=1200&height=auto&aspect=true",
    categoria: "pantalones",
    id: 19,
    tipo: "mujer",
  },
  {
    nombre: "Remera deportiva",
    descripcion: "Remera deportiva de tejido transpirable.",
    precio: 27.99,
    imagen:
      "https://portsaid.vtexassets.com/arquivos/ids/343852-1200-auto?width=1200&height=auto&aspect=true",
    categoria: "pantalones",
    id: 20,
    tipo: "mujer",
  },
  {
    nombre: "Remera deportiva",
    descripcion: "Remera deportiva de tejido transpirable.",
    precio: 27.99,
    imagen:
      "https://portsaid.vtexassets.com/arquivos/ids/343852-1200-auto?width=1200&height=auto&aspect=true",
    categoria: "pantalones",
    id: 21,
    tipo: "mujer",
  },
  {
    nombre: "Remera deportiva",
    descripcion: "Remera deportiva de tejido transpirable.",
    precio: 27.99,
    imagen:
      "https://d3ugyf2ht6aenh.cloudfront.net/stores/574/739/products/1063-1-removebg-preview1-7f50b2b13297cfd38e16812457825186-640-0.webp",
    categoria: "accesorios",
    id: 22,
    tipo: "infantil",
  },
  {
    nombre: "Remera deportiva",
    descripcion: "Remera deportiva de tejido transpirable.",
    precio: 27.99,
    imagen:
      "https://d3ugyf2ht6aenh.cloudfront.net/stores/574/739/products/1063-1-removebg-preview1-7f50b2b13297cfd38e16812457825186-640-0.webp",
    categoria: "accesorios",
    id: 23,
    tipo: "infantil",
  },
  {
    nombre: "Remera deportiva",
    descripcion: "Remera deportiva de tejido transpirable.",
    precio: 27.99,
    imagen:
      "https://d3ugyf2ht6aenh.cloudfront.net/stores/574/739/products/1063-1-removebg-preview1-7f50b2b13297cfd38e16812457825186-640-0.webp",
    categoria: "accesorios",
    id: 24,
    tipo: "infantil",
  },
  {
    nombre: "Remera deportiva",
    descripcion: "Remera deportiva de tejido transpirable.",
    precio: 27.99,
    imagen:
      "https://d3ugyf2ht6aenh.cloudfront.net/stores/574/739/products/1063-1-removebg-preview1-7f50b2b13297cfd38e16812457825186-640-0.webp",
    categoria: "accesorios",
    id: 25,
    tipo: "infantil",
  },
  {
    nombre: "Remera deportiva",
    descripcion: "Remera deportiva de tejido transpirable.",
    precio: 27.99,
    imagen:
      "https://d3ugyf2ht6aenh.cloudfront.net/stores/574/739/products/1063-1-removebg-preview1-7f50b2b13297cfd38e16812457825186-640-0.webp",
    categoria: "accesorios",
    id: 26,
    tipo: "infantil",
  },
  {
    nombre: "Remera deportiva",
    descripcion: "Remera deportiva de tejido transpirable.",
    precio: 27.99,
    imagen:
      "https://d3ugyf2ht6aenh.cloudfront.net/stores/574/739/products/1063-1-removebg-preview1-7f50b2b13297cfd38e16812457825186-640-0.webp",
    categoria: "accesorios",
    id: 27,
    tipo: "infantil",
  },
  {
    nombre: "Remera deportiva",
    descripcion: "Remera deportiva de tejido transpirable.",
    precio: 27.99,
    imagen:
      "https://d3ugyf2ht6aenh.cloudfront.net/stores/574/739/products/1063-1-removebg-preview1-7f50b2b13297cfd38e16812457825186-640-0.webp",
    categoria: "accesorios",
    id: 28,
    tipo: "infantil",
  },
  {
    nombre: "Remera deportiva",
    descripcion: "Remera deportiva de tejido transpirable.",
    precio: 27.99,
    imagen:
      "https://d3ugyf2ht6aenh.cloudfront.net/stores/574/739/products/1063-1-removebg-preview1-7f50b2b13297cfd38e16812457825186-640-0.webp",
    categoria: "accesorios",
    id: 29,
    tipo: "infantil",
  },
  {
    nombre: "Remera deportiva",
    descripcion: "Remera deportiva de tejido transpirable.",
    precio: 27.99,
    imagen:
      "https://d3ugyf2ht6aenh.cloudfront.net/stores/574/739/products/1063-1-removebg-preview1-7f50b2b13297cfd38e16812457825186-640-0.webp",
    categoria: "accesorios",
    id: 30,
    tipo: "infantil",
    pais: "bolivia",
  },
  {
    nombre: "Remera deportiva",
    descripcion: "Remera deportiva de tejido transpirable.",
    precio: 27.99,
    imagen:
      "https://d3ugyf2ht6aenh.cloudfront.net/stores/896/285/products/cabo-dad-hat-brick1-c964cedb582a8023e316673289228592-1024-1024.webp",
    categoria: "accesorios",
    id: 31,
    tipo: "accesorios",
    pais: "bolivia",
  },
  {
    nombre: "Remera deportiva",
    descripcion: "Remera deportiva de tejido transpirable.",
    precio: 27.99,
    imagen:
      "https://d3ugyf2ht6aenh.cloudfront.net/stores/896/285/products/cabo-dad-hat-brick1-c964cedb582a8023e316673289228592-1024-1024.webp",
    categoria: "accesorios",
    id: 32,
    tipo: "accesorios",
    pais: "bolivia",
  },
  {
    nombre: "Remera deportiva",
    descripcion: "Remera deportiva de tejido transpirable.",
    precio: 27.99,
    imagen:
      "https://d3ugyf2ht6aenh.cloudfront.net/stores/896/285/products/cabo-dad-hat-brick1-c964cedb582a8023e316673289228592-1024-1024.webp",
    categoria: "accesorios",
    id: 33,
    tipo: "accesorios",
    pais: "chile",
  },
  {
    nombre: "Remera deportiva",
    descripcion: "Remera deportiva de tejido transpirable.",
    precio: 27.99,
    imagen:
      "https://d3ugyf2ht6aenh.cloudfront.net/stores/896/285/products/cabo-dad-hat-brick1-c964cedb582a8023e316673289228592-1024-1024.webp",
    categoria: "accesorios",
    id: 34,
    tipo: "accesorios",
    pais: "costa rica",
  },
  {
    nombre: "Remera deportiva",
    descripcion: "Remera deportiva de tejido transpirable.",
    precio: 27.99,
    imagen:
      "https://d3ugyf2ht6aenh.cloudfront.net/stores/896/285/products/cabo-dad-hat-brick1-c964cedb582a8023e316673289228592-1024-1024.webp",
    categoria: "accesorios",
    id: 35,
    tipo: "accesorios",
  },
];
